src/Response.php

Add send content type

---

src/Response.php

Response send payload

---

src/Request.php

Request send NotFound on invalid ressource

---

src/Response.php

Add etag on send payload

---

src/Response.php

Use http_response_code in Response

---

src/Request.php

Request sendPayload with const payload

---

src/Request.php

Fixes #22
Add maxAge (86400) to constructor
Add allowedOrigin (*) to constructor

Add allowed origins to request

---

src/Request.php

gracefully accept double / in path

---

src/Request.php

Inhance Logging in Request

---

src/Request.php

Assignees: theking2
Labels: enhancement
Milestone:
Instead of throwing an exception send a BadReqeust response
Fixes #42

Send BadRequest for malformed param

---

src/Response.php

Remove xmlrpc_encode

---

src/Request.php

Kingma sbw/issue48

---

src/Request.php

Content-Type missing in allow-headers

---

src/Request.php

Regexp bug

---

src/Request.php
src/Rest.php

make Max-Age optional

---

README.md
src/Request.php
src/Response.php
src/Rest.php
src/RestInterface.php

Refactor: Move Request processing in Constructor to handleRequest

---

src/Request.php
src/Rest.php

Auto set Request::logger in Rest::__construct

---

src/Request.php
src/Response.php
src/Rest.php

Remove setting logger in Rest\Constructor

---

src/Request.php

exception to include message->value

bug Request.php

---

src/Request.php
src/Response.php

sendPayload error handling

---

src/Rest.php

make options non abstract again
